services:
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - $HOME/postgresql/dbs/openalex:/var/lib/postgresql/data
  #   networks:
  #     - spark-container-network
  #   hostname: postgres
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 4G

  # spark-thrift-server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "10000:10000"
  #   hostname: spark-thrift-server
  #   environment:
  #     - SPARK_SQL_SERVER_PORT=10000
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #     - SPARK_WAREHOUSE_DIR=${WAREHOUSE}
  #     - METASTORE_URIS=thrift://metastore:9023
  #     - SPARK_LOG_DIR=/tmp/spark-events
  #     - SPARK_DRIVER_HOST=spark-thrift-server
  #   volumes:
  #     - /tmp:/tmp
  #   networks:
  #     - spark-container-network
  #   depends_on:
  #     - metastore
  #   restart: unless-stopped
  #   entrypoint: /bin/bash -c /start_thrift_server_k2s.sh
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2"
  #         memory: 8G

  # spark-history-server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "12020:12020"
  #   hostname: spark-history-server
  #   volumes:
  #     - /tmp:/tmp
  #   networks:
  #     - spark-container-network
  #   # depends_on:
  #   #   - metastore
  #   restart: unless-stopped
  #   entrypoint: /bin/bash -c /start_history_server.sh
  #   environment:
  #     - SPARK_LOG_DIR=/tmp/spark-events
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 4G

  # shuffle-service:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7337:7337"
  #   hostname: shuffle-service
  #   volumes:
  #     - /tmp:/tmp
  #   networks:
  #     - spark-container-network
  #   # depends_on:
  #   #   - metastore
  #   restart: unless-stopped
  #   entrypoint: /bin/bash -c /start_shuffle_service.sh
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 4G

networks:
  spark-container-network:
    driver: bridge